### ISSUE TITLE
'errorCode': 1000100

### ISSUE THREAD

**Issue by yoonbird** [lmbringas/packtpub-downloader#19]
ERROR (please copy and paste in the issue)
{'message': 'jwt expired', 'errorCode': 1000100, 'errorId': 'e41ebd90-bdc2-4263-
aa2f-cdd7c9394156'}
401
Starting to download media/Building_an_RPG_with_Unity_5_x.code
Traceback (most recent call last):
  File "main.py", line 226, in <module>
    main(sys.argv[1:])
  File "main.py", line 218, in main
    download_book(filename, url)
  File "main.py", line 104, in download_book
    r = requests.get(url, stream=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\requests\sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\requests\sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\requests\models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\requests\models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps y
ou meant http://?

**Comment by BurnhamG** [comment]
Hi @yoonbird, my apologies for taking so long to address this. I believe I have some patches that should fix this problem, as well as prevent the script from creating an empty file. Here's the info from this [comment](https://github.com/lmbringas/packtpub-downloader/issues/20#issuecomment-541242654):

>Below are links to a version that is this repo's master branch with slight changes to address these problems, as well as a version that includes parallel downloading (from PR #18).
>
>Current master with patch:
>https://github.com/BurnhamG/packtpub-downloader/tree/error_fix
>
>Patch with parallel downloads:
>https://github.com/BurnhamG/packtpub-downloader/tree/async

Just let me know if you have any questions, or if you continue to see this error.
