### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by SilverPro7** [lmbringas/packtpub-downloader#24]
python main.py -e blalabla@nigde.com -p nopassword -d media -b pdf,epub,mobi,code
You are in!
Traceback (most recent call last):
  File "main.py", line 226, in <module>
    main(sys.argv[1:])
  File "main.py", line 198, in main
    books = get_books(user, is_verbose=verbose, is_quiet=quiet)
  File "main.py", line 41, in get_books
    print(f'You have {str(r.json()["count"])} books')
KeyError: 'count'

How to fix it?

**Comment by BurnhamG** [comment]
Hi @SilverPro7, some other people have run into this problem, so [here's](https://github.com/lmbringas/packtpub-downloader/issues/20#issuecomment-541242654) a comment that should hopefully help. If this doesn't help, or you're still seeing the error after trying one or both of the links there, please let me know and I'll take a look.
