### ISSUE TITLE
books can't be downloaded if the filename contains symbol <?>

### ISSUE THREAD

**Issue by reason195** [lmbringas/packtpub-downloader#34]
Starting to download G:\packt/AWS_Certified_Developer_???_Associate_Guide_-_Second_Edition.epub
Traceback (most recent call last):
  File "G:\packtpub-downloader-master\main.py", line 226, in <module>
    main(sys.argv[1:])
  File "G:\packtpub-downloader-master\main.py", line 218, in main
    download_book(filename, url)
  File "G:\packtpub-downloader-master\main.py", line 103, in download_book
    with open(filename, 'wb') as f:
OSError: [Errno 22] Invalid argument: 'G:\\packt/AWS_Certified_Developer_???_Associate_Guide_-_Second_Edition.epub'

**Comment by pablodelflo** [comment]
Hello @reason195 @lmbringas .

I found a workarround for this issue. You have to edit the **main.py** file on line 209.

Originally we have:

`book_name = book['productName'].replace(' ', '_').replace('.', '_').replace(':', '_').replace('/','')`

Change it to:

`book_name = book['productName'].replace(' ', '_').replace('.', '_').replace(':', '_').replace('/','').replace('?','')`
