### ISSUE TITLE
KeyError: 'count'

### ISSUE THREAD

**Issue by G66K-CODE** [lmbringas/packtpub-downloader#37]
packtpub-downloader    | You are in!
packtpub-downloader    | Traceback (most recent call last):
packtpub-downloader    |   File "/app/main.py", line 226, in <module>
packtpub-downloader    |     main(sys.argv[1:])
packtpub-downloader    |   File "/app/main.py", line 198, in main
packtpub-downloader    |     books = get_books(user, is_verbose=verbose, is_quiet=quiet)
packtpub-downloader    |   File "/app/main.py", line 41, in get_books
packtpub-downloader    |     print(f'You have {str(r.json()["count"])} books')
packtpub-downloader    | KeyError: 'count'

**Comment by KemeleGT** [comment]
Same error here 
Anyone knows how i can go about this? ?@imbringas

**Comment by BarehSolok** [comment]
you got this message because you do not own any products
